// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwamhzlevqlzkgevwvyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YW1oemxldnFsemtnZXZ3dnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTkwNDMsImV4cCI6MjA2ODEzNTA0M30.aLK-PScH9mFLWNpmBeHC5iG5VAC9V44gU4gLg4gb9fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});